# Generated by Django 5.1.5 on 2025-02-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMMapping',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('model_config', models.JSONField()),
                ('parameters', models.BigIntegerField()),
                ('quant_level', models.CharField(max_length=10)),
                ('context_window', models.IntegerField()),
                ('cache_bit', models.IntegerField()),
                ('cuda_overhead', models.IntegerField()),
            ],
        ),
    ]
