# Generated by Django 5.1.5 on 2025-02-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleMSeriesProcessor',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bandwidth', models.FloatField()),
            ],
        ),
    ]
