# Generated by Django 5.1.5 on 2026-03-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_applemseriesprocessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmapping',
            name='base_model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='llmmapping',
            name='file_size_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmmapping',
            name='model_format',
            field=models.CharField(default='base', max_length=10),
        ),
        migrations.AddField(
            model_name='llmmapping',
            name='repo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
